services:
  dev:
    build:
      context: .
      target: development
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  tests:
    image: tests
    build:
      context: .
      target: testing
    volumes:
      - .:/app

  tests-watch:
    image: testing-watch
    build:
      context: .
      target: testing-watch
    volumes:
      - .:/app

  coverage:
    image: coverage
    build:
      context: .
      target: coverage
    volumes:
      - .:/app
